## YAML Template.
---

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true  
    hibernate:
      ddl-auto: update
    
server:
    port: 9081
    servlet:
        context-path: /appmusic
        
logging:
   level: 
      # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error 
      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN  